spring.application.name=customer-service
server.port=8081

spring.data.mongodb.uri=mongodb+srv://rudreshcsr:DNHYb15BHSN3Lo0Q@cluster0.shfwcil.mongodb.net/device_db?retryWrites=true&w=majority&appName=Cluster0