spring.application.name=customer-service
server.port=${PORT:8081}

spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://rudreshcsr:DNHYb15BHSN3Lo0Q@cluster0.shfwcil.mongodb.net/device_db?retryWrites=true&w=majority&appName=Cluster0}